import { Types } from "mongoose";
import { DeviceStatus, FineStatus, IoTTelemetryPayload, ReservationStatus, SessionStatus, SlotStatus } from "@smart-parking/shared";
import { IoTDevice, IIoTDevice } from "../models/ioTDevice.model.js";
import { ParkingLocation } from "../models/parkingLocation.model.js";
import { ParkingSlot, IParkingSlot } from "../models/parkingSlot.model.js";
import { SensorEvent } from "../models/sensorEvent.model.js";
import { emitDeviceUpdated, emitParkingUpdated, emitReservationUpdated, emitSessionUpdated, emitSlotUpdated } from "../sockets/index.js";
import { logger } from "../utils/logger.js";
import { RFIDService } from "../services/rfid.service.js";
import { ParkingSession } from "../models/parkingSession.model.js";
import { Reservation } from "../models/reservation.model.js";
import { OverstayFine } from "../models/overstayFine.model.js";
import { ReservationStateService } from "./reservationState.service.js";
import { env } from "../config/env.js";

const MAX_CLOCK_SKEW_MS = 5 * 60 * 1000;

const parseTimestamp = (value: string | number | undefined): Date => {
  if (value === undefined) throw new Error("Telemetry timestamp is required");
  const timestamp = new Date(value);
  if (Number.isNaN(timestamp.getTime())) throw new Error("Invalid telemetry timestamp");
  if (timestamp.getTime() > Date.now() + MAX_CLOCK_SKEW_MS) throw new Error("Telemetry timestamp is too far in the future");
  return timestamp;
};

export const getParkingTelemetryStats = async (parkingLocationId: Types.ObjectId) => {
  const slots = await ParkingSlot.find({ parkingLocationId, isActive: true }).select("status");
  const count = (status: SlotStatus) => slots.filter((slot) => slot.status === status).length;
  const availableSlots = count(SlotStatus.AVAILABLE);
  const occupiedSlots = count(SlotStatus.OCCUPIED);
  const reservedSlots = count(SlotStatus.RESERVED);
  const unknownSlots = count(SlotStatus.UNKNOWN);
  const maintenanceSlots = count(SlotStatus.MAINTENANCE) + count(SlotStatus.OUT_OF_SERVICE);
  const knownPhysicalSlots = availableSlots + occupiedSlots;
  const occupancyRate = knownPhysicalSlots > 0 ? Math.round((occupiedSlots / knownPhysicalSlots) * 1000) / 10 : null;
  return { totalSlots: slots.length, availableSlots, occupiedSlots, reservedSlots, maintenanceSlots, unknownSlots, occupancyRate };
};

export class IoTIngestionService {
  private static async requireDevice(payload: IoTTelemetryPayload) {
    const parkingLocationId = payload.parkingId || payload.parkingLocationId;
    if (!parkingLocationId || !Types.ObjectId.isValid(parkingLocationId)) throw new Error("A valid parking location ID is required");
    const device = await IoTDevice.findOne({ deviceId: payload.deviceId, isActive: true });
    if (!device) throw new Error(`Device ${payload.deviceId} is not enrolled`);
    if (!device.parkingLocationId.equals(new Types.ObjectId(parkingLocationId))) {
      throw new Error(`Device ${payload.deviceId} is not assigned to parking location ${parkingLocationId}`);
    }
    return device;
  }

  private static async markOnline(device: IIoTDevice, timestamp: Date) {
    device.status = DeviceStatus.ONLINE;
    device.lastHeartbeat = timestamp;
    device.lastMessageAt = timestamp;
    await device.save();
    emitDeviceUpdated({ deviceId: device.deviceId, parkingLocationId: device.parkingLocationId.toString(), status: DeviceStatus.ONLINE, lastHeartbeat: timestamp.toISOString() });
  }

  public static async processRFIDScan(payload: IoTTelemetryPayload) {
    const timestamp = parseTimestamp(payload.timestamp);
    if (!payload.rfidUid || !payload.scannedSlotId || !payload.scanId) throw new Error("RFID scan must include a UID, scanned slot, and scan ID");
    const device = await this.requireDevice(payload);
    // ESP32 timestamps have one-second precision. Occupancy and RFID messages
    // generated by the same card tap may therefore legitimately be equal.
    if (device.lastMessageAt && timestamp.getTime() < device.lastMessageAt.getTime()) throw new Error("Stale or duplicate RFID event rejected");
    const slot = payload.scannedSlotId
      ? await ParkingSlot.findOne({
          parkingLocationId: device.parkingLocationId,
          deviceId: device._id,
          isActive: true,
          ...(Types.ObjectId.isValid(payload.scannedSlotId) ? { _id: new Types.ObjectId(payload.scannedSlotId) } : { slotNumber: payload.scannedSlotId }),
        })
      : null;
    if (!slot) throw new Error("RFID scan must identify a slot assigned to this device");
    const sensorSnapshot = payload.slots?.find((item) => item.slotId === payload.scannedSlotId);
    if (sensorSnapshot && (!slot.lastSensorUpdate || timestamp.getTime() >= slot.lastSensorUpdate.getTime())) {
      const newStatus = sensorSnapshot.occupied ? SlotStatus.OCCUPIED : SlotStatus.AVAILABLE;
      const changed = slot.status !== newStatus;
      slot.status = newStatus;
      slot.lastSensorUpdate = timestamp;
      await slot.save();
      if (changed) {
        await SensorEvent.create({ parkingLocationId: device.parkingLocationId, slotId: slot._id, deviceId: device.deviceId, eventType: sensorSnapshot.occupied ? "SLOT_OCCUPIED" : "SLOT_VACATED", occupied: sensorSnapshot.occupied, timestamp, payload });
        emitSlotUpdated({ parkingLocationId: device.parkingLocationId.toString(), slotId: slot._id.toString(), slotNumber: slot.slotNumber, status: newStatus });
      }
    }
    await this.markOnline(device, timestamp);
    return RFIDService.processDeviceScan({ parkingLocationId: device.parkingLocationId.toString(), deviceId: device.deviceId, rfidUid: payload.rfidUid, slot });
  }

  public static async processTelemetry(payload: IoTTelemetryPayload) {
    const timestamp = parseTimestamp(payload.timestamp);
    const device = await this.requireDevice(payload);
    if (payload.heartbeatOnly === true) {
      if (device.lastMessageAt && timestamp.getTime() < device.lastMessageAt.getTime()) throw new Error("Stale or duplicate heartbeat rejected");
      await this.markOnline(device, timestamp);
      return { status: "ok", message: "Heartbeat recorded" };
    }
    if (!payload.slots?.length) throw new Error("Occupancy telemetry must include slots");
    const requestedIds = payload.slots.map((item) => item.slotId);
    if (new Set(requestedIds).size !== requestedIds.length) throw new Error("Duplicate slot identifiers rejected");

    const resolved: Array<{ slot: IParkingSlot; update: { slotId: string; occupied: boolean } }> = [];
    for (const update of payload.slots) {
      const slot = await ParkingSlot.findOne({
        parkingLocationId: device.parkingLocationId,
        isActive: true,
        ...(Types.ObjectId.isValid(update.slotId) ? { _id: new Types.ObjectId(update.slotId) } : { slotNumber: update.slotId }),
      });
      if (!slot) throw new Error(`Slot ${update.slotId} is not registered for this parking location`);
      if (!slot.deviceId || !slot.deviceId.equals(device._id as Types.ObjectId)) throw new Error(`Slot ${slot.slotNumber} is not assigned to device ${device.deviceId}`);
      if (slot.status === SlotStatus.MAINTENANCE || slot.status === SlotStatus.OUT_OF_SERVICE) throw new Error(`Slot ${slot.slotNumber} is not accepting telemetry`);
      if (slot.lastSensorUpdate && timestamp.getTime() < slot.lastSensorUpdate.getTime()) throw new Error(`Stale or duplicate telemetry rejected for slot ${slot.slotNumber}`);
      resolved.push({ slot, update });
    }

    const updatedSlots: Array<{ slotId: string; slotNumber: string; status: SlotStatus }> = [];
    for (const { slot, update } of resolved) {
      const newStatus = update.occupied ? SlotStatus.OCCUPIED : SlotStatus.AVAILABLE;
      const changed = slot.status !== newStatus;
      slot.status = newStatus;
      slot.lastSensorUpdate = timestamp;
      await slot.save();
      if (!update.occupied) {
        const pendingSession = await ParkingSession.findOne({ slotId: slot._id, status: SessionStatus.CHECKOUT_PENDING, exitVerifiedAt: { $exists: true } });
        if (pendingSession) {
          const unpaidFine = await OverstayFine.exists({ sessionId: pendingSession._id, status: { $nin: [FineStatus.PAID, FineStatus.WAIVED] } });
          if (!env.REQUIRE_FINE_PAYMENT_BEFORE_EXIT || !unpaidFine) {
            const reservation = pendingSession.reservationId ? await Reservation.findById(pendingSession.reservationId) : null;
            pendingSession.status = SessionStatus.COMPLETED;
            pendingSession.checkOutTime = timestamp;
            pendingSession.durationMinutes = Math.max(0, Math.ceil((timestamp.getTime() - pendingSession.checkInTime.getTime()) / 60000));
            if (reservation) reservation.status = ReservationStatus.COMPLETED;
            await Promise.all([
              pendingSession.save(),
              reservation?.save(),
              ParkingSlot.updateOne({ _id: slot._id, currentReservationId: reservation?._id }, { $unset: { currentReservationId: 1 } }),
            ]);
            emitSessionUpdated({ sessionId: pendingSession._id.toString(), userId: pendingSession.userId.toString(), parkingLocationId: pendingSession.parkingLocationId.toString(), slotId: pendingSession.slotId.toString(), status: pendingSession.status, checkOutTime: timestamp.toISOString() });
            if (reservation) emitReservationUpdated({ reservationId: reservation._id.toString(), userId: reservation.userId.toString(), parkingLocationId: reservation.parkingLocationId.toString(), slotId: reservation.slotId.toString(), status: reservation.status });
            await ReservationStateService.publishForSlot(slot._id.toString());
          }
        }
      }
      if (changed) {
        await SensorEvent.create({ parkingLocationId: device.parkingLocationId, slotId: slot._id, deviceId: device.deviceId, eventType: update.occupied ? "SLOT_OCCUPIED" : "SLOT_VACATED", occupied: update.occupied, timestamp, payload });
        updatedSlots.push({ slotId: slot._id.toString(), slotNumber: slot.slotNumber, status: newStatus });
      }
    }

    await this.markOnline(device, timestamp);
    const stats = await getParkingTelemetryStats(device.parkingLocationId);
    await ParkingLocation.findByIdAndUpdate(device.parkingLocationId, { $set: { totalSlots: stats.totalSlots, availableSlots: stats.availableSlots, occupancy: stats.occupancyRate } });
    for (const slot of updatedSlots) emitSlotUpdated({ parkingLocationId: device.parkingLocationId.toString(), ...slot });
    if (updatedSlots.length > 0) emitParkingUpdated({ parkingLocationId: device.parkingLocationId.toString(), ...stats, updatedAt: new Date().toISOString() });
    logger.info(`Accepted physical telemetry from ${device.deviceId}; ${updatedSlots.length} occupancy state(s) changed`);
    return { status: "ok", parkingLocationId: device.parkingLocationId.toString(), updatedSlotsCount: updatedSlots.length, locationStats: stats };
  }
}
